### ISSUE TITLE
KeyError when removing interface

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/zc.relation#1]
See https://github.com/collective/collective.searchandreplace/issues/34 for an example. Last part of traceback:

```
Module z3c.relationfield.event, line 76, in updateRelations
Module zc.relation.catalog, line 546, in unindex
Module zc.relation.catalog, line 556, in unindex_doc
Module zc.relation.catalog, line 621, in _remove
KeyError: InterfaceClass Products.CMFDynamicViewFTI.interfaces.ISelectableBrowserDefault
```

@do3cc I see this post from you where you have a workaround for fixing an already broken relation catalog: http://do3.cc/blog/2012/09/264/debugging-zcrelations---broken-btrees/

Did you get anywhere with properly fixing this problem? I do see a branch https://github.com/zopefoundation/zc.relation/tree/do3cc_foot_meet_gun but nothing really happened there yet. And on master you have made this change which may help partially:
https://github.com/zopefoundation/zc.relation/commit/10b9f88ab8530ab4c0eca86416a7200d84b3e5d1

(BTW, last release is 1.0 from 2008.)

**Comment by do3cc** [comment]
Unfortunately no. Fixing this properly would take quite some time, enough to actually consider rewriting the functionality to something simpler. the underlaying packages allow much more than we actually need and we are using some features wrong (The docs even say not to use persistent  objects as keys, and we still have them)
But I don't see me working on this any time soon :-(

**Comment by do3cc** [comment]
Oh, I just noticed, my comments were with the plone packages for relations in mind, not for zc.relation

**Comment by do3cc** [comment]
This is not a zc.relation issue, it is a z3c.relationship issue. This is the bug: https://github.com/zopefoundation/z3c.relationfield/issues/4

**Comment by mauritsvanrees** [comment]
Ah, thanks for the clarification!
