### ISSUE TITLE
Revitalize package

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.relation#11]
This repository is the base implementation for `z3c.relationfield` which is used in `plone.app.relationfield`.

There is #7 trying to fix the issued in Python 3.7+ but it is stalled for months.

As this repository seems to be an integral building block of Plone, I'd like to ask for a helping hand to get it fixed.
(I have no personal interest in this repository, the only thing I feel able to do is to provide infrastructure to run the tests.)

Cc-ing to a bunch of developers coming to my mind:

@mauritsvanrees @jensens @gforcada

Feels free to invite other developers which know this package or depend on its functionality.

**Comment by icemac** [comment]
See #12 where I updated the package to `meta/config` but all tests fail there even for Python 2.7.

**Comment by jensens** [comment]
I add @pbauer as in-official "Master of Relations", @ale-rt  and @petschki to this Cc list.

**Comment by jensens** [comment]
Also: 
- Drop Python 2.7 support
- move dependency on ZODB3 to ZODB.

**Comment by icemac** [comment]
After #12 is merged we now have running tests, so only dropping Python 2 support and ZODB3 is left.

**Comment by icemac** [comment]
We have the `drop-legacy-python.py` script in `meta/config` to do the main work of dropping Python 2 support.

**Comment by ale-rt** [comment]
@icemac do you want to make a last release supporting also Py 2.7?

**Comment by icemac** [comment]
@ale-rt Done in https://pypi.org/project/zc.relation/1.2/.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zc.relation/2.0/ containing the fixes requested here.
