### ISSUE TITLE
PyPI release needed

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.relation#4]
After Python 3 support was added to this package a new release to PyPI is needed.

Could someone please cut a release or give me (`icemac`) the needed rights on PyPI?

**Comment by garyposter** [comment]
I gave you privileges. Thank you!

**Comment by icemac** [comment]
I just released https://pypi.org/project/zc.relation/1.1/. But something went wrong with the `long_description` it seems to contain the whole PKG-INFO. I'll fix this in #6.

**Comment by mgedmin** [comment]
That is a very peculiar long_description.  How did you do the upload?

**Comment by icemac** [comment]
@mgedmin I used `zest.releaser`. I never had problems like this with this tool.

**Comment by jamadden** [comment]
I think this is an unfortunate interaction stemming from [when .txt files were renamed to .rst](https://github.com/zopefoundation/zc.relation/commit/93f34df9ba7687a9bad8bff74141e658eec99e4d).

It all goes back to this line from setup.py:
```python
setup(
   ...
   description=text("README.rst"),
   ...
)
```

The `text` helper function inserts newlines at the end of .rst files:
```python
# simplified
def text(*args, **kwargs):
    # note: distutils explicitly disallows unicode for setup values :-/
    # http://docs.python.org/dist/meta-data.html
    tmp = []
    for a in args:
        if a.endswith('.rst'):
            f = open(os.path.join(*a.split('/')))
            tmp.append(f.read())
            f.close()
            tmp.append('\n\n')
        else:
             ...
    if len(tmp) == 1: # NEVER TRUE for .rst files, see above!
        res = tmp[0]
    else:
        res = ''.join(tmp)
    return res
```

So the description ends up being `'Index intransitive and transitive n-ary relationships.\n\n\n'`

Which translates to `PKG_INFO` as 
```
Metadata-Version: 2.1
Name: zc.relation
Version: 1.1
Summary: Index intransitive and transitive n-ary relationships.



Home-page: https://github.com/zopefoundation/zc.relation
Author: Gary Poster
Author-email: gary@zope.com
License: ZPL 2.1
Description: ================
        Relation Catalog
        ================
```

I know that wheel used the `email` libraries for [dealing with metadata](https://github.com/pypa/wheel/issues/178), leading to breakage, and I suspect PKG_INFO parsers did or do likewise, so the extra newlines after `Summary` would be interpreted as the end of the headers and beginning of the body. (EDIT: That's [specified by metadata 2.1](https://www.python.org/dev/peps/pep-0566/#description))  The body is what gets rendered if there's no Description key, and the body isn't valid reST (unexpected indentation on line 6, `     Relation Catalog`), so...mangled page on PyPI.

**Comment by icemac** [comment]
@jamadden Thank you for your deep analysis. I fixed the PyPI page although I needed two releases to achieve this. I should have read your analysis more care fully. Sorry.

**Comment by mgedmin** [comment]
Oh wow!  This is also a setuptools bug IMHO: it should reject newlines in the `description` field.

**Comment by mgedmin** [comment]
Filed https://github.com/pypa/setuptools/issues/1390
